name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  firebase_database: ^3.1.5
  intl: ^0.16.1
  table_calendar: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/flutter-icon.png
